### ISSUE TITLE
none of the test cases are running

### ISSUE THREAD

**Issue by vikramvi** [llatinov/selenium-samples-java#1]
Hi,

I tried running test cases with **mvn clean verify** from below directories

1. selenium-samples-java
> Invalid driver name passed as 'browser' system property , how to fix this ?

2. selenium-samples-java/cucumber-parallel
> none of the test cases were run

Please clarify how to fix these issues ?

Thanks & Regards,
Vikram

**Comment by llatinov** [comment]
Hello

As usually happens with Selenium projects driver executable and browser were out of sync, meaning Firefox was updated, where geckodriver.exe not. I've updated the Selenium bindings as well as werdrivers. Now should work.

Other issue was as that some selenium locator for site used in examples were changed, as well very often problem in web automation.

Desired browser can be passed as Java system property, e.g. -Dbrowser=CHROME. This will remove the output you are referring in 1.

Regards, Lyudmil
